name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  prettier:
    if: always()
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Lint source code with Prettier
        run: npx prettier --check "prettier --check '**/*.{js,jsx,ts,tsx}'"
